FROM amazonlinux:2
WORKDIR /build

RUN amazon-linux-extras install postgresql14
RUN yum -y install postgresql-server postgresql-server-devel git gcc jq wget tar make cmake xz bzip2

# https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-14x
# postgres14 in RDS has plv8 2.3.15
RUN set -ex \
  && git clone -b v2.3.15 --depth 1 https://github.com/plv8/plv8 \
  && cd plv8 \
  && make -j$(nproc --all) plv8_config.h || true \
  && make -j$(nproc --all) install || true
#  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so
