FROM amazonlinux:2
WORKDIR /build

RUN amazon-linux-extras install postgresql14
RUN yum -y install postgresql-server postgresql-server-devel git gcc jq wget tar make cmake xz

ENV PLV8_BRANCH=v3.2.0
ENV PLV8_VERSION=3.2
RUN set -ex && git clone --branch ${PLV8_BRANCH} --depth 1 https://github.com/plv8/plv8
RUN set -ex \
  && cd plv8 \
  && sed -i 's/cmake -Denable/CXX=clang++ CC=clang cmake -Denable/' Makefile \
  && make install || true
#  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so


