CREATE FUNCTION median(VARIADIC float8[]) RETURNS float8
     AS 'MODULE_PATHNAME', 'nocode_median'
     LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION average(VARIADIC float8[]) RETURNS float8
     AS 'MODULE_PATHNAME', 'nocode_average'
     LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION ieee_div(float8, float8) RETURNS float8
     AS 'MODULE_PATHNAME', 'nocode_ieee_div'
     LANGUAGE C IMMUTABLE STRICT;
