name: ami_build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ami_build:
    name: "Ami Build"
    runs-on: postgres-builder-32core
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Build Docker"
        run: build docker build . -f Dockerfile_ami
