name: Release

on:
  push:
    branches: ["main", "arm-build"]
    tags: [ v* ]
  # pull_request:
  #   types: [ opened, synchronize, reopened ]
  workflow_dispatch:


# this is needed for getting the github token from the organization's oauth
# app. see: tibdex/github-app-token
permissions:
  id-token: write
  contents: read

jobs:

  release:
    runs-on: ubuntu-latest
    name: "Release"
    env:
      AWS_REGION: eu-central-1
      APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.event.pull_request.head.sha || github.sha  }}
      ARTIFACTS_BUCKET: priceloop-build-artifacts-nocode
      POSTGRES_REPOSITORY: priceloop/postgres
      ECR_URL: public.ecr.aws
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: flwi-multi-postgres:${{APP_VERSION}}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
